sudo: required
language: python
services:
    - docker
script:
  - docker exec -it scikit_multilearn_dev_test_docker python3 -m pytest /home/python-dev/repo
before_install:
  - docker pull niedakh/scikit-multilearn-dev:latest
install:
  - docker run -e "MEKA_CLASSPATH=/opt/meka/lib" -v "$TRAVIS_BUILD_DIR:/home/python-dev/repo" --name scikit_multilearn_dev_test_docker -d niedakh/scikit-multilearn-dev:latest
  - find $TRAVIS_BUILD_DIR -name \*.pyc -delete