sudo: required
language: python
services:
    - docker
script:
  - docker run -v "$TRAVIS_BUILD_DIR:/home/python-dev/repo" -d niedakh/scikit-multilearn-dev:latest /bin/sh -c "python3 -m pytest /home/python-dev/repo"
before_install:
  - docker pull niedakh/scikit-multilearn-dev:latest
